scheme: Pisces

codeblock:
  # Code Highlight theme
  # Available values: normal | night | night eighties | night blue | night bright | solarized | solarized dark | galactic
  # See: https://github.com/chriskempson/tomorrow-theme
  highlight_theme: galactic
  # Add copy button on codeblock
  copy_button:
    enable: true
    # Show text copy result.
    show_result: true
    # Available values: default | flat | mac
    style: default

menu:
  home: / || fa fa-home
  archives: /archives/ || fa fa-archive
  tags: /tags/ || fas fa-tags
  apps: /apps/ || fas fa-dice-d6
  todo: /todo/ || fas fa-th-list
  friends: /friends/ || fa fa-user-friends
  about: /about/ || fa fa-child

footer:
  since: 2016
  powered: true
  beian:
    enable: true
    icp: 湘ICP备2021000702号-1
    gongan_id: 2021000702
    # gongan_num: 京公网安备 1234567890号
    # gongan_icon_url: /uploads/beian.png

google_analytics:
  tracking_id: G-VD8JQMPHR5
  only_pageview: false

darkmode: true

pjax: true

excerpt_description: true

preconnect: true
mobile_layout_economy: true

reading_progress:
  enable: true
  # Available values: left | right
  start_at: left
  # Available values: top | bottom
  position: top
  reversed: false
  color: "#37c6c0"
  height: 3px

# font:
#   # Use custom fonts families or not.
#   # Depended options: `external` and `family`.
#   enable: true

#   #   # Uri of fonts host, e.g. https://fonts.googleapis.com (Default).
#   host: https://fonts.googleapis.com

#   #   # Font options:
#   #   # `external: true` will load this font family from `host` above.
#   #   # `family: Times New Roman`. Without any quotes.
#   #   # `size: x.x`. Use `em` as unit. Default: 1 (16px)

#   #   # Global font settings used for all elements inside <body>.
#   #   global:
#   #     external: true
#   #     family: Monda
#   #     size: 1.125

#   #   # Font settings for site title (.site-title).
#   #   title:
#   #     external: true
#   #     family: Lobster Two
#   #     size:

#   #   # Font settings for headlines (<h1> to <h6>).
#   #   headings:
#   #     external: true
#   #     family: Amita
#   #     size:

#   # Font settings for posts (.post-body).
#   posts:
#     external: true
#     family: Roboto, Helvetica, Tahoma, Arial, "PingFang SC", "Hiragino Sans GB", "Microsoft YaHei", "WenQuanYi Micro Hei", "Noto Sans CJK", sans-serif
#     size: 0.8

#   #   # Font settings for <code> and code blocks.
#   codes:
#     external: true
#     family: JetBrainsMono, "Source Code Pro", Monaco, Menlo, Consolas, "Courier New", Courier, monospace
#     size: 0.64

math:
  # Default (false) will load mathjax / katex script on demand.
  # That is it only render those page which has `mathjax: true` in front-matter.
  # If you set it to true, it will load mathjax / katex srcipt EVERY PAGE.
  every_page: false

  mathjax:
    enable: true
    # Available values: none | ams | all
    tags: none

  katex:
    enable: false
    # See: https://github.com/KaTeX/KaTeX/tree/master/contrib/copy-tex
    copy_tex: false

note:
  # Note tag style values:
  #  - simple    bs-callout old alert style. Default.
  #  - modern    bs-callout new (v2-v3) alert style.
  #  - flat      flat callout style with background, like on Mozilla or StackOverflow.
  #  - disabled  disable all CSS styles import of note tag.
  style: modern
  icons: true
  # Offset lighter of background in % for modern and flat styles (modern: -12 | 12; flat: -18 | 6).
  # Offset also applied to label tag variables. This option can work with disabled note tag.
  light_bg_offset: -18

custom_file_path:
  #head: source/_data/head.njk
  #header: source/_data/header.njk
  #sidebar: source/_data/sidebar.njk
  #postMeta: source/_data/post-meta.njk
  #postBodyEnd: source/_data/post-body-end.njk
  footer: source/_data/footer.njk
  #bodyEnd: source/_data/body-end.njk
  #variable: source/_data/variables.styl
  #mixin: source/_data/mixins.styl
  #style: source/_data/styles.styl
