name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '14.x'

    - name: Setup
      run: |
        npm install hexo-cli -g
        npm install

    - name: Generate
      run: hexo clean && hexo generate

    - name: Commit
      run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git diff --quiet && git diff --staged --quiet || git commit -am 'auto commit'
          echo ::set-output name=status::success
    
    - name: 'GitHub Push'
      if: steps.commit.output.status != 'success'
      uses: ad-m/github-push-action@v0.6.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}

    - name: Deploy
      uses: burnett01/rsync-deployments@4.0
      with:
        switches: -avzr --delete --exclude="" --filter=""
        path: public/
        remote_path: /var/www/52bilibili.com/
        remote_host: 1.14.157.65
        remote_port: 873
        remote_user: ubuntu
        remote_key: ${{ secrets.DEPLOY_KEY }}
      